item {
  id: 1
  name: 'Brown Spot'
}

item {
  id: 2
  name: 'False Smut'
}

item {
  id: 3
  name: 'Leaf Folder'
}

item {
  id: 4
  name: 'Others'
}


item {
  id: 5
  name: 'Paddy Stemborer'
}

